
"""Add photo_url to audits

Revision ID: 0379b5725cee
Revises: 7a8b9c0d1e2f
Create Date: 2026-02-16 21:55:07.975400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0379b5725cee'
down_revision = '7a8b9c0d1e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_answers', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('audits', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'photo_url')
    op.drop_column('audit_answers', 'photo_url')
    # ### end Alembic commands ###
